/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Chat_UI;
import Projeto_Chat_1ºBimestre.DataStream.*;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintStream;
import static java.lang.Thread.sleep;
import java.net.InetAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author Win7
 */
public class MenuInicial extends javax.swing.JFrame {
    public ClienteUI cliente;
    public String recebido; 
    
    public void setString(String c){
        recebido = c;
    };
    
    public String getString(){
        return recebido;
    };

    public Thread Recebedor = new Thread(new Runnable(){ 
            @Override
            public void run(){ 
                while (true){ 
                    try {
                        EnviarParaTela();
                    } catch (InterruptedException ex) {
                        Logger.getLogger(MenuInicial.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    } 
                } 
            } 
        ); 
    
    
    public void EnviarParaTela() throws InterruptedException{
        sleep(150);
        if(recebido != null){
            if(recebido.contains("lista_usuarios:")){
                String[] parts = recebido.split(":");
                String[] parts2 = null;
                    parts2 = parts[1].split(";");
                        fieldUsuarios1.setText("");
                    for(int i = 0 ; i < parts2.length; i++){
                        fieldUsuarios1.append(parts2[i]+"\n");    
                    }
            }else{    
                    
            
            //fieldChat1.append("eae"+"\n");
            fieldChat1.append(recebido+"\n");
            recebido = null;
            //}
        
    }}};
    
    public MenuInicial(){
        initComponents();
    }

    private void verificarMensagens() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        fieldUsuarios = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        fieldChat = new javax.swing.JTextArea();
        enviarfield = new javax.swing.JTextField();
        getPORT = new javax.swing.JTextField();
        buttonConnect = new javax.swing.JButton();
        labelPORT = new javax.swing.JLabel();
        labelIP = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        fieldUsuarios1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        fieldChat1 = new javax.swing.JTextArea();
        getIP1 = new javax.swing.JTextField();
        buttonEnviar = new javax.swing.JButton();

        jLabel3.setText("Usuários conectados");

        fieldUsuarios.setEditable(false);
        fieldUsuarios.setColumns(20);
        fieldUsuarios.setRows(5);
        jScrollPane2.setViewportView(fieldUsuarios);

        fieldChat.setEditable(false);
        fieldChat.setColumns(20);
        fieldChat.setRows(5);
        jScrollPane1.setViewportView(fieldChat);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        getPORT.setText("6666");
        getPORT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getPORTActionPerformed(evt);
            }
        });

        buttonConnect.setText("Connectar");
        buttonConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConnectActionPerformed(evt);
            }
        });

        labelPORT.setText("PORT:");

        labelIP.setText("IP:");

        jLabel4.setText("Usuários conectados:");

        fieldUsuarios1.setEditable(false);
        fieldUsuarios1.setColumns(20);
        fieldUsuarios1.setRows(5);
        jScrollPane3.setViewportView(fieldUsuarios1);

        fieldChat1.setEditable(false);
        fieldChat1.setColumns(20);
        fieldChat1.setRows(5);
        jScrollPane4.setViewportView(fieldChat1);

        getIP1.setText("127.0.0.1");

        buttonEnviar.setText("Enviar");
        buttonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enviarfield, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonEnviar))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPORT)
                        .addGap(10, 10, 10))
                    .addComponent(labelIP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(getIP1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(buttonConnect))
                    .addComponent(getPORT, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(398, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enviarfield)
                            .addComponent(buttonEnviar)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getPORT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPORT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonConnect)
                    .addComponent(getIP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIP))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getPORTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getPORTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getPORTActionPerformed

    private void buttonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnviarActionPerformed
        // TODO add your handling code here:]

                    String enviar = enviarfield.getText();
                    cliente.saida.println(enviar);
                    enviarfield.setText("");

    }//GEN-LAST:event_buttonEnviarActionPerformed

    private void buttonConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConnectActionPerformed
        String cara = getIP1.getText();
        String[] parts;
        parts = cara.split("[.]");
        byte[] ipAddr = new byte[]{
            Byte.parseByte(parts[0]),Byte.parseByte(parts[1]),Byte.parseByte(parts[2]),Byte.parseByte(parts[3])
        };

        InetAddress ip = null;
        //int ports = 0;
        
        String d = getPORT.getText();
        int ports = Integer.parseInt(d);
        
        try {
            ip = InetAddress.getByAddress(ipAddr);
        } catch (UnknownHostException ex) {
            Logger.getLogger(MenuInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            cliente = new ClienteUI(ip,ports,this);
        } catch (IOException ex) {
            Logger.getLogger(MenuInicial.class.getName()).log(Level.SEVERE, null, ex);
        }

                          //Recebedor.start();
    }//GEN-LAST:event_buttonConnectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
  
        

       
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConnect;
    private javax.swing.JButton buttonEnviar;
    public javax.swing.JTextField enviarfield;
    private javax.swing.JTextArea fieldChat;
    private javax.swing.JTextArea fieldChat1;
    private javax.swing.JTextArea fieldUsuarios;
    private javax.swing.JTextArea fieldUsuarios1;
    public javax.swing.JTextField getIP1;
    private javax.swing.JTextField getPORT;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelIP;
    private javax.swing.JLabel labelPORT;
    // End of variables declaration//GEN-END:variables
}
